# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vicky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='received',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
