# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicky', '0002_auto_20170710_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
