# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vicky', '0004_auto_20170710_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='message_id',
            new_name='alert_id',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='raw_xml',
            new_name='message_xml',
        ),
    ]
