# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vicky', '0005_auto_20170710_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_sender',
            field=models.CharField(default='unknown', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
